### ISSUE TITLE
PIO for APRS sine wave generation

### ISSUE THREAD

**Issue by kellyostrom** [Project-CETI/whale-tag-recovery#13]
Currently the sine wave for the APRS transmissions are using a simply loop functionality with a busy wait. There are some concerns that there is error delay accumulating from this as per #12, and if that's true, if the PIO could be used to generate the sine wave instead because of the higher precision in terms of timing. The PIO would allow better syncing with the clock to have a more accurate sine wave.

**Comment by msalinoh** [comment]
No longer relevant to latest STM32 based recovery board. Sinewave generation handled via DAC DMA with clock scaling for precise timing.
